name: cli-calculator
title: CLI Calculator
base: core22
version: '1.6'
license: Apache-2.0
source-code:
  - https://github.com/Benedek553/cli-calculator
issues:
  - https://github.com/Benedek553/cli-calculator/issues
summary: Simple CLI calculator
icon: icon.png
description: |
  CLI Calculator is a lightweight yet full-featured command-line toolkit that lets you evaluate expressions, convert number bases, solve equations, work with matrices, and inspect divisors without ever leaving the terminal. It targets developers, power users, and anyone who appreciates deterministic C++ utilities.

  **Highlights**

  * Evaluate arbitrarily long expressions with `+ - * / x :`, parentheses, factorial, and built-in math functions such as `sin`, `cos`, `log`, `sqrt`, `tan`, `exp`, and `sinh`
  * Convert signed integers between binary (`0b`), decimal, and hexadecimal (`0x`) inputs or outputs in one command
  * Solve linear (`a * x + b = 0`) and quadratic (`a * x^2 + b * x + c = 0`) equations, including complex roots, with guided prompts
  * Run matrix workflows (add, subtract, multiply) for arbitrarily sized matrices with validation before each operation
  * Visualize number series by entering them manually or loading CSV columns, previewing the ASCII graph, then exporting a labeled PNG chart
  * Perform prime factorization and divisor lookups optimized for large integers
  * Inspect or edit persisted variables (`vars.toml`) so you can reuse values in future sessions or in scripts

  **CLI workflows**

  * `cli-calculator` launches the interactive menu (matrix tools, equation solver, prime factorization, divisors, variable manager, etc.)
  * `cli-calculator --repl` opens an instant read–eval–print loop with history (`:history`, `!<n>`) and autocompletion-like shortcuts
  * `cli-calculator --eval "2*(3+5)"` evaluates expressions headlessly; combine with `--output json|yaml|xml` for script-friendly responses
  * `cli-calculator --convert 10 16 42`, `--divisors 120`, `--prime-factorization 32768`, and `--square-root 625` provide single-shot utilities without entering the menu
  * `cli-calculator --batch tasks.txt` executes a list of commands with helper directives (`@set`, `@input`, `@include`, `@if`, `@unset`) so you can automate repetitive calculations
  * Graph utility (menu option 10) walks you through picking manual/CSV data, ASCII preview height, and the PNG filename so you can share charts without leaving the terminal

  **Usage tips**

  * Variables and batch directives let you reuse previous results; numerical CLI flags accept variable names as arguments
  * `--variables` (or `--list-variables`) prints the persisted values, and `--version` reports the build without launching the UI
  * ANSI colors are enabled by default; disable them with `--no-color`
  * Works great inside scripts, containers, CI pipelines, or minimal environments—there are no runtime dependencies beyond libstdc++
grade: stable
confinement: strict

apps:
  cli-calculator:
    command: bin/calculator
    plugs: [home]

parts:
  cli-calculator:
    plugin: cmake
    source: .
    cmake-parameters:
      - -DBUILD_TESTING=OFF
    override-pull: |
      craftctl default
      # Remove host-generated CMake artifacts that break in-snap builds
      find . -name CMakeCache.txt -delete
      find . -name CMakeFiles -type d -prune -exec rm -rf {} +
      rm -rf build
    build-packages:
      - build-essential
      - cmake
      - g++
    stage-packages:
      - libstdc++6
    organize:
      usr/local/bin/calculator: bin/calculator
