name: CMake pipeline for Windows build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (MSYS2)
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-boost
            mingw-w64-x86_64-qt5-base
            mingw-w64-x86_64-qt5-tools
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-harfbuzz
            mingw-w64-x86_64-icu
            mingw-w64-x86_64-pcre2
            mingw-w64-x86_64-graphite2
            mingw-w64-x86_64-freetype
            mingw-w64-x86_64-gettext
            mingw-w64-x86_64-bzip2
            mingw-w64-x86_64-brotli
            mingw-w64-x86_64-libiconv
            mingw-w64-x86_64-md4c
            mingw-w64-x86_64-angleproject
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-boost-libs	  
            mingw-w64-x86_64-double-conversion
            mingw-w64-x86_64-libpng
            mingw-w64-x86_64-zstd
            mingw-w64-x86_64-glib2
            mingw-w64-x86_64-gettext-runtime

      - name: Configure CMake
        shell: msys2 {0}
        run: |
          cmake -B build -G "Ninja" -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_PREFIX_PATH=/mingw64 \
            -DCMAKE_C_COMPILER=gcc \
            -DCMAKE_CXX_COMPILER=g++

      - name: Build with Ninja
        shell: msys2 {0}
        run: |
          cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Run tests
        shell: msys2 {0}
        run: |
          cd build
          ctest --output-on-failure

      - name: Deploy application with windeployqt
        shell: msys2 {0}
        run: |
          mkdir -p dist
          cp build/src/calculator_gui.exe dist/
          windeployqt --dir dist dist/calculator_gui.exe
          cp ${{github.workspace}}/build/src/libgcc_s_seh-1.dll dist
          cp ${{github.workspace}}/build/src/zlib1.dll dist
          cp ${{github.workspace}}/build/src/libboost*.dll dist
          cp ${{github.workspace}}/build/src/libstdc++-6.dll dist
          cp ${{github.workspace}}/build/src/libwinpthread-1.dll dist
          cp ${{github.workspace}}/build/src/Qt5Concurrent.dll dist
          cp ${{github.workspace}}/build/src/Qt5Core.dll dist
          cp ${{github.workspace}}/build/src/Qt5DBus.dll dist
          cp ${{github.workspace}}/build/src/Qt5Gui.dll dist
          cp ${{github.workspace}}/build/src/Qt5Network.dll dist
          cp ${{github.workspace}}/build/src/Qt5OpenGL.dll dist
          cp ${{github.workspace}}/build/src/Qt5PrintSupport.dll dist
          cp ${{github.workspace}}/build/src/Qt5Sql.dll dist
          cp ${{github.workspace}}/build/src/Qt5Test.dll dist
          cp ${{github.workspace}}/build/src/Qt5Widgets.dll dist
          cp ${{github.workspace}}/build/src/Qt5Xml.dll dist
          cp ${{github.workspace}}/build/src/libharfbuzz-0.dll dist
          cp ${{github.workspace}}/build/src/libharfbuzz-gobject-0.dll dist
          cp ${{github.workspace}}/build/src/libharfbuzz-subset-0.dll dist
          cp ${{github.workspace}}/build/src/libmd4c.dll dist
          cp ${{github.workspace}}/build/src/libdouble-conversion.dll dist
          cp ${{github.workspace}}/build/src/libicuin78.dll dist
          cp ${{github.workspace}}/build/src/libicudt78.dll dist
          cp ${{github.workspace}}/build/src/libicuio78.dll dist
          cp ${{github.workspace}}/build/src/libicutest78.dll dist
          cp ${{github.workspace}}/build/src/libicutu78.dll dist
          cp ${{github.workspace}}/build/src/libicuuc78.dll dist
          cp ${{github.workspace}}/build/src/libpcre2-16-0.dll dist
          cp ${{github.workspace}}/build/src/libpcre2-32-0.dll dist
          cp ${{github.workspace}}/build/src/libpcre2-8-0.dll dist
          cp ${{github.workspace}}/build/src/libpcre2-posix-3.dll dist
          cp ${{github.workspace}}/build/src/libpng16-16.dll dist
          cp ${{github.workspace}}/build/src/libzstd.dll dist
          cp ${{github.workspace}}/build/src/libgraphite2.dll dist
          cp ${{github.workspace}}/build/src/libfreetype-6.dll dist
          cp ${{github.workspace}}/build/src/libglib-2.0-0.dll dist
          cp ${{github.workspace}}/build/src/libbrotlicommon.dll dist
          cp ${{github.workspace}}/build/src/libbrotlidec.dll dist
          cp ${{github.workspace}}/build/src/libbrotlienc.dll dist
          cp ${{github.workspace}}/build/src/libintl-8.dll dist
          cp ${{github.workspace}}/build/src/libbz2-1.dll dist
          cp ${{github.workspace}}/build/src/libiconv-2.dll dist
          cp ${{github.workspace}}/build/src/qdirect2d.dll dist
          cp ${{github.workspace}}/build/src/qminimal.dll dist
          cp ${{github.workspace}}/build/src/qoffscreen.dll dist
          cp ${{github.workspace}}/build/src/qwindows.dll dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: calculator-windows-dist
          path: dist/
